version: '3.8'

services:
  assembly-database:
    build: database/.
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: assembly
        MYSQL_USER: assembly
        MYSQL_PASSWORD: assembly
    volumes:
      - ~/var/lib/mysql

#  assembly-service:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      ASSEMBLY_DATABASE_URL: assembly-database
#    depends_on:
#      - assembly-database