CREATE DATABASE IF NOT EXISTS assembly;

CREATE TABLE IF NOT EXISTS agenda (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  description VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS `session` (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  agenda_id INTEGER NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  result VARCHAR(4),
  FOREIGN KEY (agenda_id) REFERENCES agenda(id)
);

CREATE TABLE IF NOT EXISTS vote (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  agenda_id INTEGER NOT NULL,
  vote VARCHAR(3) NOT NULL,
  associated_id BIGINT NOT NULL,
  associated_cpf VARCHAR(14),
  FOREIGN KEY (agenda_id) REFERENCES agenda(id),
  UNIQUE (agenda_id, associated_id)
);
